set(command "/usr/local/bin/cmake;-P;/home/mazzer/work/nordic/sdk/nrf5_SDK_for_Mesh_v2.0.1_build/nRF5_SDK_15.0.0_a53641a/src/nRF5_SDK-stamp/download-nRF5_SDK.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "/usr/local/bin/cmake;-P;/home/mazzer/work/nordic/sdk/nrf5_SDK_for_Mesh_v2.0.1_build/nRF5_SDK_15.0.0_a53641a/src/nRF5_SDK-stamp/verify-nRF5_SDK.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "/usr/local/bin/cmake;-P;/home/mazzer/work/nordic/sdk/nrf5_SDK_for_Mesh_v2.0.1_build/nRF5_SDK_15.0.0_a53641a/src/nRF5_SDK-stamp/extract-nRF5_SDK.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
